#!/bin/bash

light_green='\033[1;32m'
light_red='\033[1;31m'
light_yellow='\033[1;33m'
no_color='\033[0m'

function echo-info  { printf "\r${light_green} %s${no_color}\n" "$*"; }
function echo-warn  { printf "\r${light_yellow} %s${no_color}\n" "$*"; }
function echo-skip  { printf "\r${light_yellow} %s${no_color}\n" "$*"; }
function echo-ok    { printf "\r${light_green} %s${no_color}\n" "$*"; }
function echo-fail  { printf "\r${light_red} %s${no_color}\n" "$*"; }

function installing  { echo-info "Installing $1..."; }
function installnote { echo-info "   $1"; }
function skipping    { echo-skip "   already installed; skipping."; }
function success     { echo-ok   "   success!"; }

pkg_install () {
    local distro;
    local cmd;
    local usesudo

    declare -A pkgmgr
    pkgmgr=( \
      [arch]="pacman -S --noconfirm" \
      [alpine]="apk add --no-cache" \
      [debian]="apt-get install -y" \
      [ubuntu]="apt-get install -y" \
    )

    distro=$(cat /etc/os-release | tr [:upper:] [:lower:] | grep -Poi '(debian|ubuntu|red hat|centos|arch|alpine)' | uniq)
    cmd="${pkgmgr[$distro]}"
    [[ ! $cmd ]] && return 1
    if [[ $1 ]]; then
        [[ ! $EUID -eq 0 ]] && usesudo=sudo
        echo-info Installing package with: $usesudo $cmd $@
        $usesudo $cmd $@
    else
        echo $cmd
    fi
}
