#!/usr/bin/env bash
#
# Initialize a home directory.
#
# The scripts has to be run from the ar-settings repository.
#
set -euo pipefail

# For skipping sections, use this trick:
#
#   cat >/dev/null <<LABEL
#
# see the brilliant answer here: https://stackoverflow.com/a/45538151

secret_bin=$(pwd)/home/.local/bin/secret
temp_dir=$(mktemp -d -t "ar-init-home.XXXXXXXXXX")

source ./home/.local/share/ar/helpers.sh

echo_info "Creating directories"
mkdir -p $HOME/.local/bin
mkdir -p $HOME/tmp
mkdir -p $HOME/git

pushd ./home > /dev/null

diff_cmd="git difftool --no-index"

files=()
while IFS= read -r -d '' file; do
    files+=("$file")
done < <(
    # Find the main config files, EXCLUDING .enc and .gpg files
    find . -maxdepth 1 \( -name .bashrc -o -name .bash_profile -o -name .bash_aliases \) -not -name '*.enc' -not -name '*.gpg' -type f -print0
    # Find ALL files (EXCLUDING .enc and .gpg) within the .bashrc.d directory and its subdirectories
    find .bashrc.d -not -name '*.enc' -not -name '*.gpg' -type f -print0
)

echo_debug "The files are:"
for file in "${files[@]}"; do
  echo_debug "- $file"
done

init_normal_files "${files[@]}"

echo_info "Making $HOME/.local/bin files executable"
find "$HOME/.local/bin" -type f -and -not -executable -exec chmod u+x {} ';'

encrypted_files=()
while IFS= read -r -d '' file; do
    encrypted_files+=("$file")
done < <(
    find .bashrc.d \( -name '*.enc' -o -name '*.gpg' \) -type f -print0
)

echo_debug "Encrypted files are:"
for file in "${encrypted_files[@]}"; do
  echo_debug "- $file"
done

init_encrypted_files "${encrypted_files[@]}"

popd > /dev/null
