#!/usr/bin/env bash
#
# Initialize i3 within this system.
#
# The scripts has to be run from the ar-settings repository.
#
set -euo pipefail

# For skipping sections, use this trick:
#
#   cat >/dev/null <<LABEL
#
# see the brilliant answer here: https://stackoverflow.com/a/45538151

source ./home/.local/share/ar/helpers.sh

# For xdg-desktop-portal-gtk see
#   https://forum.endeavouros.com/t/i3wm-xdg-desktop-portal-impl/58165/3
echo_info "Installing i3 and related packages"
pkg_install i3-wm i3blocks i3exit i3lock i3status i3-battery-popup-git \
            dunst rofi conky pcmanfm-gtk3 flameshot \
            xdg-desktop-portal-gtk \
            keepassxc  accountsservice \
            ttf-jetbrains-mono ttf-noto-nerd \
            lxsession-gtk3 lightdm-gtk-greeter lightdm onboard
