#!/usr/bin/env bash

set -euo pipefail

# For skipping sections, use this trick:
#
#   cat >/dev/null <<HUB
#
# see the brilliant answer here: https://stackoverflow.com/a/45538151

source ./helpers

echo-info "Updating apt packages..."
sudo apt update

echo-info "Installing packages..."
sudo apt install rxvt-unicode qasmixer scrot cmake arandr silversearcher-ag zeal \
     xsel docker docker-compose exuberant-ctags tree byzanz \
     rlwrap markdown xclip xbacklight texinfo meld python3-pip cryptsetup global \
     exiftool cdiff texlive-latex-base texlive-latex-extra wicd-cli wicd-curses wich-gdk \
     console-data shellcheck

echo-info "Installing i3 packages..."
sudo apt install i3 rofi
