#!/usr/bin/env bash

set -euo pipefail

source ./helpers

# From https://www.reddit.com/r/emacs/comments/v2ib5c/selfcompiling_emacs_what_about_the_recommended/

echo-info "Installing Emacs dev packages..."
sudo apt install build-essential libgtk-3-dev libgnutls28-dev libtiff5-dev libgif-dev libjpeg-dev libpng-dev libxpm-dev libncurses-dev texinfo

echo-info "Cloning Emacs repository..."
git clone git://git.sv.gnu.org/emacs.git $HOME/git/emacs

pushd $HOME/git/emacs > /dev/null

git tag --list
git checkout emacs-28.3
./autogen.sh

# Copied and tweaked from the AUR
#   https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=emacs28-git
./configure --with-json --with-x-toolkit=gtk3 --with-native-compilation --with-cairo \
            --enable-gtk-deprecation-warnings --with-gnutls=no \
            --without-gconf --without-gsettings --without-xaw3d \
            --without-libotf --without-m17n-flt --without-gpm --without-pop \
            --with-gif=ifavailable --with-jpeg=ifavailable --with-png=ifavailable --with-tiff=ifavailable \
            --enable-checking=structs --with-x  \
            --prefix "$HOME/.local"
make bootstrap
make NATIVE_FULL_AOT=1
make install

popd > /dev/null
