#!/usr/bin/env bash

set -euo pipefail

# For skipping sections, use this trick:
#
#   cat >/dev/null <<HUB
#
# see the brilliant answer here: https://stackoverflow.com/a/45538151

source ./helpers

# ruby-ruby_parser is needed for cucumber.el/feature-mode

declare -a packages
packages=(pandoc-bin zeal gtk-recordmydesktop \
          nordvpn-bin backblaze-b2 yarn-completion-git \
          cask ruby-ruby_parser adr-tools)

for pkg in "${packages[@]}"; do
    echo -n "Install $pkg from AUR (y/n)? "
    stty raw -echo ; answer=$(head -c 1) ; stty sane

    if echo "$answer" | grep -iq "^y" ;then
        echo-info "\nInstalling $pkg..."
        pamac build "$pkg"
    else
        echo-skip "Skipping."
    fi
done
