#!/usr/bin/env bash
set -euo pipefail

# For skipping sections, use this trick:
#
#   cat >/dev/null <<HUB
#
# see the brilliant answer here: https://stackoverflow.com/a/45538151

tmpdir=$(mktemp -d -t "ar-settings-install-scripts.XXXXXXXXXX")
bindir=$(systemd-path user-binaries)

source ./home/.local/share/ar/helpers.sh

# cat >/dev/null <<GOTO_ASDF

target_arch=linux-amd64

function latest_releases {
  local github_coords="$1"
  curl -sL "https://api.github.com/repos/$github_coords/releases/latest"
}

function maybe_install_sdkman {
  installing "sdkman"
  if [ -d "$SDKMAN_DIR" ]; then
    skipping
  else
    curl -sfL "https://get.sdkman.io" | bash
    success
  fi
}

installing "eldev"
if command -v eldev >/dev/null 2>&1; then
    skipping
else
    curl -o- -fsSL https://raw.github.com/doublep/eldev/master/bin/eldev > $bindir/eldev \
        && chmod u+x $bindir/eldev
    success
fi

installing "intellij idea community edition"
if command -v idea.sh >/dev/null 2>&1; then
  skipping
else
  pushd $tmpdir >/dev/null

  curl -fsSL -o- "https://download.jetbrains.com/product?platform=linux&code=IIC&latest" > idea.tar.gz
  tar -xvzf idea.tar.gz -C $xdg_data_home_dir >/dev/null
  idea_dir=$(find $xdg_data_home_dir -type d -name 'idea*')

  if [ ! -d "$idea_dir" ]; then
    echo_fail "Cannot retrieve idea local dir. This is likely a bug."
  else
    ln -s "$idea_dir/bin/idea.sh" $bindir/idea.sh
    mkdir -p $xdg_data_home_dir/applications

    cat << END > $xdg_data_home_dir/applications/idea.desktop
[Desktop Entry]
Type=Application
Terminal=false
Exec=$idea_dir/bin/idea.sh
Name=IntelliJ IDEA CE
Icon=$idea_dir/bin/idea.png
END
  fi

  popd
fi

# GOTO_ASDF

echo_info "Installing asdf"
pkg_install asdf-vm

asdf plugin-add java
asdf plugin-add maven

asdf plugin add clojure
asdf plugin add babashka
asdf plugin add clj-kondo
asdf plugin-add zprint
asdf plugin add process-compose https://github.com/martino/asdf-process-compose.git

asdf install
